#16713220 set up heroku build
andela/king-kong-ah-frontend pull request #13
Opened 2019-07-08 17:37 UTC by akinyeleolat

#### What does this PR do?

- These set up for Heroku deployment

#### Description of task to be completed?

- npm install dependencies
- setup app.js
- setup heroku procFile

#### How should this be manually tested?

  - $ git clone ```https://github.com/andela/king-kong-ah-frontend.git```
  - $ npm install
  - $ npm run build
  - $ node app.js
#### Any background context you want to provide?

- You would need npm to run this application
- you can check the default/initial deployment here ```https://king-kong-ah-frontend-staging.herokuapp.com```

#### What are the relevant pivotal tracker stories?

- PT Story link - [#16713220](https://www.pivotaltracker.com/story/show/16713220)

#### Screenshots (if appropriate)

2019-07-08 17:46 UTC, benfluleck commented on Procfile
> +web: node app.js
Space needed here

2019-07-08 17:46 UTC, benfluleck commented on app.json
> +  }
Space needed here

2019-07-08 17:47 UTC, benfluleck commented on package.json
> +    "cors": "^2.8.5",
why is this a server ?

2019-07-09 09:12 UTC, EmmanuelSage approved these changes

2019-07-09 14:27 UTC, frankly034 approved these changes

2019-07-09 15:03 UTC, Sojisoyoye approved these changes

2019-07-09 15:30 UTC, benfluleck requested changes
Where is my deployment branch to test features

2019-07-09 16:24 UTC, merged