#167191395 setup link atom
andela/king-kong-ah-frontend pull request #18
Opened 2019-07-10 11:41 UTC by frankly034

#### What does this PR do?

- This PR sets up a Link atom with styleguide

#### Description of task to be completed?

- setup link atom
- setup styleguidist for the link
- write tests for the link atom

#### How should this be manually tested?

  - $ git clone https://github.com/andela/king-kong-ah-frontend.git
  - $ npm install
  - $ npm test

#### Any background context you want to provide?

- You would need npm to run this application

#### What are the relevant pivotal tracker stories?

- PT Story link - [#167191395](https://www.pivotaltracker.com/story/show/167191395)

#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/31358867/60966350-f1518800-a30f-11e9-9b9d-a52ce5630a69.png)

2019-07-10 17:51 UTC, Sojisoyoye approved these changes

2019-07-10 20:38 UTC, akinyeleolat approved these changes

2019-07-11 11:34 UTC, benfluleck commented on src/components/UI/atoms/Link/Link.jsx
> +    href={href || '#'}
Put this is defaultprops please.

2019-07-11 11:43 UTC, benfluleck requested changes

2019-07-11 11:43 UTC, benfluleck commented on src/components/UI/atoms/Link/Link.jsx
> +    background: ${isTag === true && '#F4EDED'};
just `isTag && '#F4EDED' `should work

2019-07-11 11:43 UTC, benfluleck commented on src/components/UI/atoms/Link/Link.jsx
> +    width: ${isTag === true && '25.8rem'};
Please correct all other instances

2019-07-11 11:43 UTC, benfluleck commented on src/components/UI/atoms/Link/Link.jsx
> +    padding: 0;
I expect logic for internal and external links. e.g. links to other sites vs links to places in your app. Something link this
```
 return isExternal ? (
    <TextLink.External {...linkProps} href={to} target={'_blank'}>
      {innerContainer}
    </TextLink.External>
  ) : (
    <TextLink.Internal {...linkProps} to={to}>
      {innerContainer}
    </TextLink.Internal>
  )
```

2019-07-11 11:43 UTC, benfluleck commented on src/components/UI/atoms/Link/Link.jsx
> +    isTag,
Can a link be disabled? 🤔

2019-07-11 11:43 UTC, benfluleck commented on src/components/UI/atoms/Link/Link.jsx
> +    href={href || '#'}
Don't use href use Link from `react-router-dom` so you have access to the apps internal routes. You might need to mock Router for the tests as I don't think you are allowed to render links in isolation

2019-07-14 21:30 UTC, benfluleck commented on src/components/UI/atoms/StyledLink/StyledLink.spec.js
> +      <MemoryRouter>
Please look at your colleagues' tests, I expect you component tests not to have repeated logic

2019-07-14 21:30 UTC, benfluleck requested changes
Feedback left

2019-07-15 10:33 UTC, benfluleck approved these changes

2019-07-15 10:34 UTC, merged