#167189243 create image atoms
andela/king-kong-ah-frontend pull request #20
Opened 2019-07-10 17:06 UTC by akinyeleolat

#### What does this PR do?

- This PR creates Image component atom

#### Description of task to be completed?

- create an image component
- write tests for the component
- create a style guide for the component

#### How should this be manually tested?

  - $ git clone https://github.com/andela/king-kong-ah-frontend.git
  - $ npm install
  - $ npm test
  - $ npm run styleguide

#### Any background context you want to provide?

- You would need npm to run this application

#### What are the relevant pivotal tracker stories?

- PT Story link - [#167189243](https://www.pivotaltracker.com/story/show/167189243)

#### Screenshots (if appropriate)
<img width="1437" alt="Screenshot 2019-07-10 at 6 00 16 PM" src="https://user-images.githubusercontent.com/19696366/60989284-73a47100-a33d-11e9-992e-906332bb70c5.png">

2019-07-10 18:19 UTC, Eazybee approved these changes

2019-07-10 21:39 UTC, frankly034 approved these changes

2019-07-10 21:43 UTC, mosinmiloluwa01 approved these changes

2019-07-10 21:48 UTC, Sojisoyoye approved these changes

2019-07-11 11:15 UTC, benfluleck commented on src/components/UI/atoms/Image/Image.jsx
> +    src={ImageUrl}
change to `imageUrl`

2019-07-11 11:15 UTC, benfluleck commented on src/components/UI/atoms/Image/Image.jsx
> +    borderColor={borderColor}/>;
Put the closing tag on a new line

2019-07-11 11:16 UTC, benfluleck commented on src/components/UI/atoms/Image/Image.jsx
> +  ImageUrl: PropTypes.string.isRequired,
change to format above

2019-07-11 11:17 UTC, benfluleck commented on src/components/UI/atoms/Image/Image.jsx
> +    src={ImageUrl}
I think it would make sense to define a default placeholder here if no imageUrl is defined

2019-07-11 11:17 UTC, benfluleck commented on src/components/UI/atoms/Image/Image.jsx
> +  altText: PropTypes.string,
It is good practice to do an altText this is particularly good for accessibility for blind users

2019-07-11 11:23 UTC, benfluleck commented on src/components/UI/atoms/Image/Image.spec.js
> +        ImageUrl='https://assets-ouch.icons8.com/preview/501/57c82ec0-5e6d-423e-b594-5d93a5f5f44b.png'
Please pass the props in like we did in the backend by using a function. There is too much repetition here.
e.g.

```
cons setup = props = {
  const defaultProps = {
   `props you are passing in`
}

const utils = render(<Image {...defaultProps} {...props} />)

return {
 ...utils
}

}
```

2019-07-11 11:24 UTC, benfluleck commented on src/styles/variables/border.js
> +  noRadius: '0%',
why is this in here ?.  What's the difference between no border-radius and none

2019-07-11 11:24 UTC, benfluleck commented on src/styles/variables/colorPalette.js
> +  default: '1px solid #ddd',
Keep casing consistent

2019-07-11 11:25 UTC, benfluleck commented on src/styles/variables/shadows.js
> +  icon: '0px 4px 1px rgba(0, 0, 0, 0.1)',
Keep colors consistent use hex

2019-07-11 11:26 UTC, benfluleck commented on webpack/webpack.common.js
> +      '<image>':path.resolve(__dirname,'../src/img'),
All images should be a `public/assets/images` folder

2019-07-11 14:20 UTC, benfluleck commented on src/components/UI/atoms/Image/Image.jsx
> +  width: ${width} || '100%';
unless you are using a boolean to conditionally render please use default props to initialize to 100%

2019-07-11 14:23 UTC, benfluleck requested changes

2019-07-11 14:23 UTC, benfluleck commented on src/styles/variables/colorPalette.js
> +  primary: '1px solid #B02091',
default and primary keys, this naming doesn't make a lot of sense. I would expect the default to be used app wide. When would I use `primary`

2019-07-11 14:23 UTC, benfluleck commented on src/components/UI/atoms/Image/Image.spec.js
> +    expect(container).toBeTruthy();
this test should be checking ImageURl not the container

2019-07-11 14:23 UTC, benfluleck commented on src/components/UI/atoms/Image/Image.spec.js
> +    expect(container).toBeTruthy();
This should be checking for the border color not the container

2019-07-11 14:23 UTC, benfluleck commented on src/components/UI/atoms/Image/Image.spec.js
> +    expect(container).toBeTruthy();
How many times will you check for the same thing

2019-07-11 18:30 UTC, benfluleck commented on src/components/UI/atoms/Image/Image.jsx
> +    boxShadow={boxShadow}
I think box-shdow should have a defaultProp

2019-07-11 18:31 UTC, benfluleck requested changes
Changes requested

2019-07-12 09:05 UTC, benfluleck submitted a review, later dismissed

2019-07-12 11:29 UTC, benfluleck approved these changes

2019-07-12 11:29 UTC, merged