#167276162 Create inputForm Field molecule
andela/king-kong-ah-frontend pull request #26
Opened 2019-07-13 18:37 UTC by akinyeleolat

#### What does this PR do?

- This PR sets up an Input Form field molecule with styleguide

#### Description of task to be completed?

- setup input form field molecule
- setup styleguidist for the input form field molecule
- write tests for the input form field molecule
- refactor divider to display inline
- add web pack molecule module resolver
- add jest config molecule module resolver
- add molecule sections to style guide configuration

#### How should this be manually tested?

  - $ git clone https://github.com/andela/king-kong-ah-frontend.git
  - $ npm install
  - $ npm test

#### Any background context you want to provide?

- You would need npm to run this application

#### What are the relevant pivotal tracker stories?

- PT Story link - [#167276162](https://www.pivotaltracker.com/story/show/167276162)

#### Screenshots (if appropriate)
<img width="1432" alt="Screenshot 2019-07-13 at 7 25 18 PM" src="https://user-images.githubusercontent.com/19696366/61175259-fe86a500-a5a3-11e9-9c60-ec8edf155737.png">

2019-07-14 14:03 UTC, frankly034 approved these changes

2019-07-14 15:38 UTC, Sojisoyoye approved these changes

2019-07-14 21:13 UTC, benfluleck commented on src/components/UI/molecules/InputFormField/InputFormField.jsx
> +  return (
There should be a space here

2019-07-14 21:14 UTC, benfluleck commented on src/components/UI/molecules/InputFormField/InputFormField.jsx
> +        && <span><Text color='error' fontSize='small' display='block'>
I expect the color to be red not error

2019-07-14 21:15 UTC, benfluleck commented on src/components/UI/molecules/InputFormField/InputFormField.jsx
> +      <label htmlFor={name}>
Do a Label atom.

2019-07-14 21:18 UTC, benfluleck requested changes

2019-07-14 21:18 UTC, benfluleck commented on src/components/UI/molecules/InputFormField/InputFormField.spec.js
> +    expect(container).toBeTruthy();
This is not the correct test I expect a test for one of the props

2019-07-14 21:18 UTC, benfluleck commented on src/components/UI/molecules/InputFormField/InputFormField.spec.js
> +    const { container } = setUp({ errorMessage: 'first name is required' });
This is not the correct test I expect a test for one of the props

2019-07-16 11:31 UTC, benfluleck approved these changes

2019-07-16 11:31 UTC, merged