#167212749 create page layout
andela/king-kong-ah-frontend pull request #32
Opened 2019-07-16 09:38 UTC by mosinmiloluwa01

#### What does this PR do?
This PR creates page layout

#### Description of task to be completed?
- create page layout template
- create header content molecule
- create header organism
- add header to page layout

#### How should this be manually tested?
- run `npm install`
- run `npm start` on your console

#### Any background context you want to provide?
user must have node installed

#### What are the relevant pivotal tracker stories?
[167212749](https://www.pivotaltracker.com/story/show/167212749)

#### Screenshots (if appropriate)
<img width="1436" alt="Screenshot 2019-07-16 at 10 34 40 AM" src="https://user-images.githubusercontent.com/41510712/61283925-d5d5f980-a7b5-11e9-985d-5502f27bd6d8.png">

2019-07-16 13:59 UTC, akinyeleolat approved these changes

2019-07-16 14:00 UTC, akinyeleolat commented
Fix the merge conflicts. It Looks Good to me.

2019-07-17 15:30 UTC, Sojisoyoye approved these changes

2019-07-17 18:09 UTC, benfluleck requested changes

2019-07-17 18:09 UTC, benfluleck commented on src/components/UI/atoms/InputField/InputField.jsx
> +  id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
Why would this ever be a number 🤔

2019-07-17 18:09 UTC, benfluleck commented on src/components/UI/molecules/Headers/HeaderNavigation.jsx
> +const HeaderNavigation = ({ navItems }) => {
```suggestion
const HeaderNavigation = ({ navItems }) => (
    <FlexContainer
      padding="zero"
      justifyContent="flex-end"
      containerWidth="searchBarWidth"
      alignItems="flex-end"
      flexDirection="row"
    >
      <Fragment>{navItems.map(items => items)}</Fragment>
    </FlexContainer>
  );
```

2019-07-17 18:09 UTC, benfluleck commented on src/components/UI/atoms/Button/Button.jsx
> +const { spacing } = themes;
Put this at line 5

2019-07-17 18:09 UTC, benfluleck commented on src/components/UI/molecules/Headers/HeaderNavigation.spec.js
> +      <MemoryRouter>
This should be abstracted out to a setup function

2019-07-17 18:09 UTC, benfluleck commented on src/components/UI/organisms/Header/Header.jsx
> +const Header = ({ navItems }) => {
Please remove the return as shown above

2019-07-17 18:09 UTC, benfluleck commented on src/components/UI/organisms/Header/Header.spec.js
> +          <Text>Hello world</Text>
This should be in a setup function

2019-07-17 18:09 UTC, benfluleck commented on src/components/pages/homepage/Homepage.jsx
> +
Remove the space please

2019-07-17 18:09 UTC, benfluleck commented on src/components/pages/homepage/Homepage.jsx
> +import PageLayout from '../../templates/pageLayout';
Keep the casing consistent for the folder structure /HomePage/HomePage.jsx

2019-07-17 18:09 UTC, benfluleck commented on src/components/pages/homepage/Homepage.jsx
> +export default Homepage;
```suggestion
export default HomePage;
```

2019-07-17 18:09 UTC, benfluleck commented on src/components/templates/PageLayout.spec.js
> +          <Text
Text with props not with html elements

2019-07-17 18:09 UTC, benfluleck commented on src/components/templates/pageLayout.jsx
> +        <Loader type="Rings" color="#B02091" height="100" width="100" />
Abstract this in one component and import it as Loader

2019-07-17 18:09 UTC, benfluleck commented on src/components/templates/pageLayout.jsx
> +  const [isLoaded, setIsLoaded] = useState(initialState);
A better name would be `isLoading` and `setIsLoading`

2019-07-17 18:09 UTC, benfluleck commented on src/components/templates/pageLayout.jsx
> +  const dataLoader = async () => {
Please rename this like a function

2019-07-17 18:09 UTC, benfluleck commented on src/components/templates/pageLayout.jsx
> +  callback: () => {
```suggestion
  callback: () => {}
```

2019-07-17 18:09 UTC, benfluleck commented on src/core/routes.js
> +import HomePage from '<pages>/homepage/Homepage';
Please keep the naming connsistent

2019-07-17 18:09 UTC, benfluleck commented on src/helpers/dummyLoader.js
> +const loadData = async (millisecond = 3000) => {
What is this doing here

2019-07-17 18:09 UTC, benfluleck commented on src/helpers/headerMapper.js
> +      <StyledLink key={i} marginleft="sm" to={links[component].action}>
index not i

2019-07-17 18:09 UTC, benfluleck commented on src/helpers/headerMapper.js
> +      <StyledLink key={i} marginleft="sm" to={links[component].location}>
index not i

2019-07-17 18:09 UTC, benfluleck commented on src/helpers/headerMapper.js
> +          key={i}
why does the button take a key

2019-07-17 18:09 UTC, benfluleck commented on src/helpers/headerMapper.js
> +        key={i}
Why is the key and id the same

2019-07-18 17:54 UTC, benfluleck commented on src/components/templates/PageLayout/PageLayout.jsx
> +  const retrieveData = async () => {
This is too generic, retrieve what Data ?

2019-07-18 17:54 UTC, benfluleck commented on src/components/templates/PageLayout/PageLayout.jsx
> +  const retrieveData = async () => {
pageData

2019-07-19 05:58 UTC, benfluleck approved these changes

2019-07-19 05:59 UTC, merged