#167531845 Create article card row
andela/king-kong-ah-frontend pull request #48
Opened 2019-07-26 13:10 UTC by akinyeleolat

2019-07-31 14:08 UTC, mosinmiloluwa01 requested changes
Good job so far, but It'll be nice to populate those cards with actual data coming from the back-end

2019-07-31 14:08 UTC, mosinmiloluwa01 commented on src/components/UI/organisms/DashboardWelcome/DashboardWelcome.jsx
> +const DashboardWelcome = () => (
i think this should be something like `WriteArticleSection`

2019-08-01 11:20 UTC, benfluleck commented on src/components/UI/organisms/ArticleCardRow/ArticleCardRow.jsx
> +  articleCardItem,
You are already in articleCard rename to items

2019-08-01 11:21 UTC, benfluleck commented on src/components/UI/organisms/ArticleCardRow/ArticleCardRow.md
> +        title='Featured Article'
tabs are off here

2019-08-01 22:15 UTC, benfluleck approved these changes

2019-08-01 22:15 UTC, merged